apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weathermap-go
spec:
  template:
    metadata:
      labels:
        run: weathermap-go
    spec:
      containers:
      - name: weathermap-go
        image:  gcr.io/jntlserv0/weathermap_go:0.8
        ports:
        - containerPort: 8080
